export const CHANGE_IMAGE_TYPE = 'CHANGE_IMAGE_TYPE';
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION';
export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const INIT_STATE = 'INIT_STATE';
export const CHANGE_GUTTERS = 'CHANGE_GUTTERS';
export const CHANGE_COLUMN_WIDTH = 'CHANGE_COLUMN_WIDTH';
export const CHANGE_RANDOM_SIZE = 'CHANGE_RANDOM_SIZE';
