export const OPEN_SETTINGS = 'OPEN_SETTINGS';
export const CLOSE_SETTINGS = 'CLOSE_SETTINGS';
export const INIT_STATE = 'INIT_STATE';
export const CHANGE_GUTTERS = 'CHANGE_GUTTERS';
export const CHANGE_COLUMN_WIDTH = 'CHANGE_COLUMN_WIDTH';
export const CHANGE_SEARCHING_VALUE = 'CHANGE_SEARCHING_VALUE';
