import { Album, Photo, User } from '../types';

export const users: User[] = [
  {
    id: 1,
    name: 'Leanne Graham',
    username: 'Bret',
    email: 'Sincere@april.biz',
    address: {
      street: 'Kulas Light',
      suite: 'Apt. 556',
      city: 'Gwenborough',
      zipcode: '92998-3874',
      geo: {
        lat: '-37.3159',
        lng: '81.1496',
      },
    },
    phone: '1-770-736-8031 x56442',
    website: 'hildegard.org',
    company: {
      name: 'Romaguera-Crona',
      catchPhrase: 'Multi-layered client-server neural-net',
      bs: 'harness real-time e-markets',
    },
  },
  {
    id: 2,
    name: 'Ervin Howell',
    username: 'Antonette',
    email: 'Shanna@melissa.tv',
    address: {
      street: 'Victor Plains',
      suite: 'Suite 879',
      city: 'Wisokyburgh',
      zipcode: '90566-7771',
      geo: {
        lat: '-43.9509',
        lng: '-34.4618',
      },
    },
    phone: '010-692-6593 x09125',
    website: 'anastasia.net',
    company: {
      name: 'Deckow-Crist',
      catchPhrase: 'Proactive didactic contingency',
      bs: 'synergize scalable supply-chains',
    },
  },
  {
    id: 3,
    name: 'Clementine Bauch',
    username: 'Samantha',
    email: 'Nathan@yesenia.net',
    address: {
      street: 'Douglas Extension',
      suite: 'Suite 847',
      city: 'McKenziehaven',
      zipcode: '59590-4157',
      geo: {
        lat: '-68.6102',
        lng: '-47.0653',
      },
    },
    phone: '1-463-123-4447',
    website: 'ramiro.info',
    company: {
      name: 'Romaguera-Jacobson',
      catchPhrase: 'Face to face bifurcated interface',
      bs: 'e-enable strategic applications',
    },
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    username: 'Karianne',
    email: 'Julianne.OConner@kory.org',
    address: {
      street: 'Hoeger Mall',
      suite: 'Apt. 692',
      city: 'South Elvis',
      zipcode: '53919-4257',
      geo: {
        lat: '29.4572',
        lng: '-164.2990',
      },
    },
    phone: '493-170-9623 x156',
    website: 'kale.biz',
    company: {
      name: 'Robel-Corkery',
      catchPhrase: 'Multi-tiered zero tolerance productivity',
      bs: 'transition cutting-edge web services',
    },
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    username: 'Kamren',
    email: 'Lucio_Hettinger@annie.ca',
    address: {
      street: 'Skiles Walks',
      suite: 'Suite 351',
      city: 'Roscoeview',
      zipcode: '33263',
      geo: {
        lat: '-31.8129',
        lng: '62.5342',
      },
    },
    phone: '(254)954-1289',
    website: 'demarco.info',
    company: {
      name: 'Keebler LLC',
      catchPhrase: 'User-centric fault-tolerant solution',
      bs: 'revolutionize end-to-end systems',
    },
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    username: 'Leopoldo_Corkery',
    email: 'Karley_Dach@jasper.info',
    address: {
      street: 'Norberto Crossing',
      suite: 'Apt. 950',
      city: 'South Christy',
      zipcode: '23505-1337',
      geo: {
        lat: '-71.4197',
        lng: '71.7478',
      },
    },
    phone: '1-477-935-8478 x6430',
    website: 'ola.org',
    company: {
      name: 'Considine-Lockman',
      catchPhrase: 'Synchronised bottom-line interface',
      bs: 'e-enable innovative applications',
    },
  },
  {
    id: 7,
    name: 'Kurtis Weissnat',
    username: 'Elwyn.Skiles',
    email: 'Telly.Hoeger@billy.biz',
    address: {
      street: 'Rex Trail',
      suite: 'Suite 280',
      city: 'Howemouth',
      zipcode: '58804-1099',
      geo: {
        lat: '24.8918',
        lng: '21.8984',
      },
    },
    phone: '210.067.6132',
    website: 'elvis.io',
    company: {
      name: 'Johns Group',
      catchPhrase: 'Configurable multimedia task-force',
      bs: 'generate enterprise e-tailers',
    },
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    username: 'Maxime_Nienow',
    email: 'Sherwood@rosamond.me',
    address: {
      street: 'Ellsworth Summit',
      suite: 'Suite 729',
      city: 'Aliyaview',
      zipcode: '45169',
      geo: {
        lat: '-14.3990',
        lng: '-120.7677',
      },
    },
    phone: '586.493.6943 x140',
    website: 'jacynthe.com',
    company: {
      name: 'Abernathy Group',
      catchPhrase: 'Implemented secondary concept',
      bs: 'e-enable extensible e-tailers',
    },
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    username: 'Delphine',
    email: 'Chaim_McDermott@dana.io',
    address: {
      street: 'Dayna Park',
      suite: 'Suite 449',
      city: 'Bartholomebury',
      zipcode: '76495-3109',
      geo: {
        lat: '24.6463',
        lng: '-168.8889',
      },
    },
    phone: '(775)976-6794 x41206',
    website: 'conrad.com',
    company: {
      name: 'Yost and Sons',
      catchPhrase: 'Switchable contextually-based project',
      bs: 'aggregate real-time technologies',
    },
  },
  {
    id: 10,
    name: 'Clementina DuBuque',
    username: 'Moriah.Stanton',
    email: 'Rey.Padberg@karina.biz',
    address: {
      street: 'Kattie Turnpike',
      suite: 'Suite 198',
      city: 'Lebsackbury',
      zipcode: '31428-2261',
      geo: {
        lat: '-38.2386',
        lng: '57.2232',
      },
    },
    phone: '024-648-3804',
    website: 'ambrose.net',
    company: {
      name: 'Hoeger LLC',
      catchPhrase: 'Centralized empowering task-force',
      bs: 'target end-to-end models',
    },
  },
];

export const albums: Album[] = [
  {
    userId: 1,
    id: 1,
    title: 'quidem molestiae enim',
  },
  {
    userId: 1,
    id: 2,
    title: 'sunt qui excepturi placeat culpa',
  },
  {
    userId: 1,
    id: 3,
    title: 'omnis laborum odio',
  },
  {
    userId: 1,
    id: 4,
    title: 'non esse culpa molestiae omnis sed optio',
  },
  {
    userId: 1,
    id: 5,
    title: 'eaque aut omnis a',
  },
  {
    userId: 1,
    id: 6,
    title: 'natus impedit quibusdam illo est',
  },
  {
    userId: 1,
    id: 7,
    title: 'quibusdam autem aliquid et et quia',
  },
  {
    userId: 1,
    id: 8,
    title: 'qui fuga est a eum',
  },
  {
    userId: 1,
    id: 9,
    title: 'saepe unde necessitatibus rem',
  },
  {
    userId: 1,
    id: 10,
    title: 'distinctio laborum qui',
  },
];

export const photos: Photo[] = [
  {
    albumId: 8,
    id: 351,
    title: 'molestias debitis cum',
    url: 'https://via.placeholder.com/600/9ae7cb',
    thumbnailUrl: 'https://via.placeholder.com/150/9ae7cb',
  },
  {
    albumId: 8,
    id: 352,
    title: 'atque aut aut nemo eum qui rem eaque suscipit',
    url: 'https://via.placeholder.com/600/df14ab',
    thumbnailUrl: 'https://via.placeholder.com/150/df14ab',
  },
  {
    albumId: 8,
    id: 353,
    title: 'quia consequatur fugit atque est saepe',
    url: 'https://via.placeholder.com/600/44e038',
    thumbnailUrl: 'https://via.placeholder.com/150/44e038',
  },
  {
    albumId: 8,
    id: 354,
    title: 'quidem aut earum',
    url: 'https://via.placeholder.com/600/5498f2',
    thumbnailUrl: 'https://via.placeholder.com/150/5498f2',
  },
  {
    albumId: 8,
    id: 355,
    title: 'minima ea qui adipisci quo ipsa',
    url: 'https://via.placeholder.com/600/b28568',
    thumbnailUrl: 'https://via.placeholder.com/150/b28568',
  },
  {
    albumId: 8,
    id: 356,
    title: 'velit aut qui alias',
    url: 'https://via.placeholder.com/600/bdba4',
    thumbnailUrl: 'https://via.placeholder.com/150/bdba4',
  },
  {
    albumId: 8,
    id: 357,
    title: 'architecto aperiam maxime reprehenderit et cupiditate ipsa',
    url: 'https://via.placeholder.com/600/a41675',
    thumbnailUrl: 'https://via.placeholder.com/150/a41675',
  },
  {
    albumId: 8,
    id: 358,
    title: 'doloribus magnam iste eos',
    url: 'https://via.placeholder.com/600/affe00',
    thumbnailUrl: 'https://via.placeholder.com/150/affe00',
  },
  {
    albumId: 8,
    id: 359,
    title: 'dolor nisi incidunt fuga blanditiis dicta placeat',
    url: 'https://via.placeholder.com/600/27a49e',
    thumbnailUrl: 'https://via.placeholder.com/150/27a49e',
  },
  {
    albumId: 8,
    id: 360,
    title: 'et laudantium quas',
    url: 'https://via.placeholder.com/600/699458',
    thumbnailUrl: 'https://via.placeholder.com/150/699458',
  },
  {
    albumId: 8,
    id: 361,
    title: 'odio iure cum iusto aut ullam aliquam praesentium',
    url: 'https://via.placeholder.com/600/73a23c',
    thumbnailUrl: 'https://via.placeholder.com/150/73a23c',
  },
  {
    albumId: 8,
    id: 362,
    title: 'neque quasi ea quia et',
    url: 'https://via.placeholder.com/600/9c8f57',
    thumbnailUrl: 'https://via.placeholder.com/150/9c8f57',
  },
  {
    albumId: 8,
    id: 363,
    title: 'rem sed quam',
    url: 'https://via.placeholder.com/600/ee7b2c',
    thumbnailUrl: 'https://via.placeholder.com/150/ee7b2c',
  },
  {
    albumId: 8,
    id: 364,
    title: 'et sit repudiandae qui',
    url: 'https://via.placeholder.com/600/8da619',
    thumbnailUrl: 'https://via.placeholder.com/150/8da619',
  },
  {
    albumId: 8,
    id: 365,
    title: 'qui officia necessitatibus debitis et sunt quis non minus',
    url: 'https://via.placeholder.com/600/39cac2',
    thumbnailUrl: 'https://via.placeholder.com/150/39cac2',
  },
  {
    albumId: 8,
    id: 366,
    title: 'qui et quia nisi',
    url: 'https://via.placeholder.com/600/976641',
    thumbnailUrl: 'https://via.placeholder.com/150/976641',
  },
  {
    albumId: 8,
    id: 367,
    title: 'id voluptatem non ut sapiente',
    url: 'https://via.placeholder.com/600/8b45ea',
    thumbnailUrl: 'https://via.placeholder.com/150/8b45ea',
  },
  {
    albumId: 8,
    id: 368,
    title: 'quaerat labore aut ducimus incidunt ex',
    url: 'https://via.placeholder.com/600/94182d',
    thumbnailUrl: 'https://via.placeholder.com/150/94182d',
  },
  {
    albumId: 8,
    id: 369,
    title: 'neque perspiciatis sint vero non qui',
    url: 'https://via.placeholder.com/600/77e4a2',
    thumbnailUrl: 'https://via.placeholder.com/150/77e4a2',
  },
  {
    albumId: 8,
    id: 370,
    title: 'rerum non quia dolore',
    url: 'https://via.placeholder.com/600/6d53ce',
    thumbnailUrl: 'https://via.placeholder.com/150/6d53ce',
  },
  {
    albumId: 8,
    id: 371,
    title: 'adipisci asperiores aperiam',
    url: 'https://via.placeholder.com/600/7a4c0f',
    thumbnailUrl: 'https://via.placeholder.com/150/7a4c0f',
  },
  {
    albumId: 8,
    id: 372,
    title: 'ratione omnis fugiat sit fuga',
    url: 'https://via.placeholder.com/600/9c1b1e',
    thumbnailUrl: 'https://via.placeholder.com/150/9c1b1e',
  },
  {
    albumId: 8,
    id: 373,
    title: 'eum dicta deleniti porro',
    url: 'https://via.placeholder.com/600/6a6136',
    thumbnailUrl: 'https://via.placeholder.com/150/6a6136',
  },
  {
    albumId: 8,
    id: 374,
    title: 'ullam aut consequatur libero provident et porro',
    url: 'https://via.placeholder.com/600/dd420e',
    thumbnailUrl: 'https://via.placeholder.com/150/dd420e',
  },
  {
    albumId: 8,
    id: 375,
    title:
      'voluptas repudiandae totam dolores voluptatem tempora et assumenda ducimus',
    url: 'https://via.placeholder.com/600/8eb5c2',
    thumbnailUrl: 'https://via.placeholder.com/150/8eb5c2',
  },
  {
    albumId: 8,
    id: 376,
    title: 'est exercitationem aliquam omnis quia quas qui qui dolor',
    url: 'https://via.placeholder.com/600/24d0d1',
    thumbnailUrl: 'https://via.placeholder.com/150/24d0d1',
  },
  {
    albumId: 8,
    id: 377,
    title: 'illum architecto rerum rerum',
    url: 'https://via.placeholder.com/600/bf47cb',
    thumbnailUrl: 'https://via.placeholder.com/150/bf47cb',
  },
  {
    albumId: 8,
    id: 378,
    title: 'veritatis quos vel omnis error',
    url: 'https://via.placeholder.com/600/c74808',
    thumbnailUrl: 'https://via.placeholder.com/150/c74808',
  },
  {
    albumId: 8,
    id: 379,
    title: 'quaerat rerum non',
    url: 'https://via.placeholder.com/600/ea74e',
    thumbnailUrl: 'https://via.placeholder.com/150/ea74e',
  },
  {
    albumId: 8,
    id: 380,
    title: 'voluptates earum dolor perferendis et',
    url: 'https://via.placeholder.com/600/6be8c1',
    thumbnailUrl: 'https://via.placeholder.com/150/6be8c1',
  },
  {
    albumId: 8,
    id: 381,
    title: 'sed quo et et nemo earum omnis quia',
    url: 'https://via.placeholder.com/600/627b42',
    thumbnailUrl: 'https://via.placeholder.com/150/627b42',
  },
  {
    albumId: 8,
    id: 382,
    title: 'iusto nam atque facilis est eos',
    url: 'https://via.placeholder.com/600/36f93e',
    thumbnailUrl: 'https://via.placeholder.com/150/36f93e',
  },
  {
    albumId: 8,
    id: 383,
    title: 'doloribus est assumenda eligendi cum asperiores earum vel',
    url: 'https://via.placeholder.com/600/6f3eae',
    thumbnailUrl: 'https://via.placeholder.com/150/6f3eae',
  },
  {
    albumId: 8,
    id: 384,
    title: 'aut quia ad earum consequatur',
    url: 'https://via.placeholder.com/600/d94fb7',
    thumbnailUrl: 'https://via.placeholder.com/150/d94fb7',
  },
  {
    albumId: 8,
    id: 385,
    title: 'blanditiis labore fugiat eum esse dolores inventore',
    url: 'https://via.placeholder.com/600/696ef',
    thumbnailUrl: 'https://via.placeholder.com/150/696ef',
  },
  {
    albumId: 8,
    id: 386,
    title: 'sequi autem fugiat ab incidunt mollitia',
    url: 'https://via.placeholder.com/600/6b51f3',
    thumbnailUrl: 'https://via.placeholder.com/150/6b51f3',
  },
  {
    albumId: 8,
    id: 387,
    title: 'et quam explicabo molestiae fugiat ipsa eum nesciunt quae',
    url: 'https://via.placeholder.com/600/747986',
    thumbnailUrl: 'https://via.placeholder.com/150/747986',
  },
  {
    albumId: 8,
    id: 388,
    title: 'quos tempore nihil rerum rerum aut libero',
    url: 'https://via.placeholder.com/600/8661f8',
    thumbnailUrl: 'https://via.placeholder.com/150/8661f8',
  },
  {
    albumId: 8,
    id: 389,
    title: 'sapiente illum vel adipisci aliquid quia',
    url: 'https://via.placeholder.com/600/122741',
    thumbnailUrl: 'https://via.placeholder.com/150/122741',
  },
  {
    albumId: 8,
    id: 390,
    title: 'reprehenderit nesciunt delectus',
    url: 'https://via.placeholder.com/600/7df63c',
    thumbnailUrl: 'https://via.placeholder.com/150/7df63c',
  },
  {
    albumId: 8,
    id: 391,
    title: 'eos reprehenderit nesciunt sit aut',
    url: 'https://via.placeholder.com/600/7ff922',
    thumbnailUrl: 'https://via.placeholder.com/150/7ff922',
  },
  {
    albumId: 8,
    id: 392,
    title: 'ut placeat amet veritatis impedit dolorem dolorem',
    url: 'https://via.placeholder.com/600/be4c',
    thumbnailUrl: 'https://via.placeholder.com/150/be4c',
  },
  {
    albumId: 8,
    id: 393,
    title: 'eveniet qui et',
    url: 'https://via.placeholder.com/600/f0d8ad',
    thumbnailUrl: 'https://via.placeholder.com/150/f0d8ad',
  },
  {
    albumId: 8,
    id: 394,
    title: 'possimus iure voluptas laborum',
    url: 'https://via.placeholder.com/600/236552',
    thumbnailUrl: 'https://via.placeholder.com/150/236552',
  },
  {
    albumId: 8,
    id: 395,
    title: 'eveniet sapiente aut ut',
    url: 'https://via.placeholder.com/600/f119b1',
    thumbnailUrl: 'https://via.placeholder.com/150/f119b1',
  },
  {
    albumId: 8,
    id: 396,
    title: 'est veniam ut quod sit quae itaque saepe fugit',
    url: 'https://via.placeholder.com/600/bc4c9a',
    thumbnailUrl: 'https://via.placeholder.com/150/bc4c9a',
  },
  {
    albumId: 8,
    id: 397,
    title: 'sint eos veritatis numquam modi est',
    url: 'https://via.placeholder.com/600/57c7c3',
    thumbnailUrl: 'https://via.placeholder.com/150/57c7c3',
  },
  {
    albumId: 8,
    id: 398,
    title: 'aperiam repellat sunt quibusdam aut provident esse',
    url: 'https://via.placeholder.com/600/9a4811',
    thumbnailUrl: 'https://via.placeholder.com/150/9a4811',
  },
  {
    albumId: 8,
    id: 399,
    title: 'magni quo nisi',
    url: 'https://via.placeholder.com/600/8c4173',
    thumbnailUrl: 'https://via.placeholder.com/150/8c4173',
  },
  {
    albumId: 8,
    id: 400,
    title: 'sit a cumque ipsum',
    url: 'https://via.placeholder.com/600/f86d1f',
    thumbnailUrl: 'https://via.placeholder.com/150/f86d1f',
  },
];
